<?php
namespace Admin\Security\Handle;

use Admin\Entity\BackendUser;
use Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse;
use Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Created by PhpStorm.
 * User: Marquis
 * Date: 2018/8/20
 * Time: 下午9:58
 */
class AuthenticationSuccessHandle extends AuthenticationSuccessHandler
{
	/**
	 * @param UserInterface|BackendUser $user
	 * @param null $jwt
	 * @return \Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationSuccessResponse|\Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse
	 */
	public function handleAuthenticationSuccess(UserInterface $user, $jwt = null)
	{
		if ($user->getEnabled()) {
			return parent::handleAuthenticationSuccess($user, $jwt); // TODO: Change the autogenerated stub
		} else {
			$response = new JWTAuthenticationFailureResponse();

			return $response;
		}
	}
}